feat: Add asset language property
linz/stac pull request #173
Opened 2021-11-18 02:43 UTC by l0b0

2021-11-18 20:36 UTC, MitchellPaff submitted a review, later dismissed

2021-11-22 01:53 UTC, billgeo requested changes
LGTM, except needs some README goodness?

2021-11-22 02:14 UTC, billgeo approved these changes

2021-11-22 19:35 UTC, amfage approved these changes

2021-11-22 19:36 UTC, merged