feat: fields.json
linz/stac pull request #197
Opened 2021-12-02 22:03 UTC by MDavidson17

## Summary
In order to use pystac to summarise the historical imagery extensions we need to create and publish our own fields.json. 

This fields.json file **appends** all historical imagery related fields to the end of the default fields.json linked above.
**Appended lines: `43-47` & `867-904`**

## Background
When exploring options of how to generate the summaries for the historical imagery metadata pytac.Summarizer.summaries() looked beneficial: https://pystac.readthedocs.io/en/latest/_modules/pystac/summaries.html

This class, however, takes a link to a fields.json, if one is not provided a default one is used: https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields/fields-normalized.json

See this link for an explaination of stac field options: https://github.com/stac-utils/stac-fields
for example: `'v'` = value/array `'r'`=range

2021-12-03 00:30 UTC, amfage approved these changes

2021-12-03 00:31 UTC, amfage approved these changes
Not quite sure if this would be OK in the long term as it will be hard to keep this file in sync.
Perhaps we can extend the summaries functionality in Pystac to enable us to use an additional fields file just for us?

2021-12-05 19:04 UTC, paulfouquet reviewed
Is there a way to extend a `json schema`?

2021-12-05 20:48 UTC, MDavidson17 commented
> Is there a way to extend a `json schema`?

hmm I'm not sure but that would likely be much cleaner. I'll look into it. 

Alternatively to generate the fields.json I wrote a smaller json file with just the fields to append (I uploaded it as a gist [here](https://gist.github.com/MDavidson17/6a5643bbc732908504ed24ffe05e13fb)) and wrote [this](https://gist.github.com/MDavidson17/63a0bf8fb1ba7b161ca07586119ded25) script to merge this with the 'official' STAC fields.json. Following a process similar to this might also be a way forward

2021-12-06 00:04 UTC, blacha commented
> > Is there a way to extend a `json schema`?
> 
> hmm I'm not sure but that would likely be much cleaner. I'll look into it.
> 
> Alternatively to generate the fields.json I wrote a smaller json file with just the fields to append (I uploaded it as a gist [here](https://gist.github.com/MDavidson17/6a5643bbc732908504ed24ffe05e13fb)) and wrote [this](https://gist.github.com/MDavidson17/63a0bf8fb1ba7b161ca07586119ded25) script to merge this with the 'official' STAC fields.json. Following a process similar to this might also be a way forward

would be a good option to just check that script into a `/scripts/import-fields-json.js`  or something

2021-12-06 03:06 UTC, dwsilk commented on .github/workflows/feilds.yaml
> +name: Build Fields
typo in filename ->  `fields.yaml`

2021-12-06 03:19 UTC, MDavidson17 commented
@amfage, @dwsilk, @paulfouquet, @blacha 
After a discussion, the process for generating the fields.json file has been included and modified.

The `.github/workflows/fields.yaml` file is triggered when a push to a branch inlcudes changes to the `./fields/custom-fields.json` file. 

the yaml file runs `./fields/import-fields-json.js` which merges the `custom-field.json` file specifically with `1.0.0-beta.10` version of stac fields. https://cdn.jsdelivr.net/npm/@radiantearth/stac-fields@1.0.0-beta.10/fields.json

The new `fields.json` file is pushed by github actions to the current banch. 

**note:** this is my first time writing both a js script and a github actions yaml file. So please make suggestions for improvements :+1: 
**note 2:** is

>  is triggered when a push to a branch inlcudes changes to the `./fields/custom-fields.json` file.

the correct time to trigger an update on fields.json?

2021-12-06 03:39 UTC, amfage approved these changes

2021-12-06 04:29 UTC, blacha commented on fields/import-fields-json.js
> +      console.log(JSON.stringify(extendedSchema));
if you use `JSON.stringify(extendedSchema, null, 2)` it will format the output for you too.

2021-12-06 04:46 UTC, amfage requested changes

2021-12-06 04:46 UTC, amfage commented on .github/workflows/fields.yaml
> +  push:
Had a conversation with @dwsilk - he thought that the script could be triggered on push to your branch and also on push to master, looks like you can use `branches-ignore` to exclude `master`.
[https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags)

2021-12-06 20:42 UTC, amfage approved these changes
:thumbsup:

2021-12-06 21:16 UTC, paulfouquet commented on fields/import-fields-json.js
> +    console.log(err.message);
This won't avoid the script to run and `./fields/fields.json` will contain the error log. Raise an error instead?

2021-12-07 02:04 UTC, amfage approved these changes

2021-12-08 21:47 UTC, paulfouquet approved these changes
Looks good!

2021-12-08 23:21 UTC, merged