ci: make consistent urls
linz/stac pull request #31
Opened 2021-09-16 22:38 UTC by blacha

- ci: create release pipeline
- ci: ensure all the schemas are located at the right place

2021-09-16 23:47 UTC, paulfouquet requested changes
A couple of spelling to review

2021-09-16 23:47 UTC, paulfouquet commented on extensions/template/README.md
> +  <https://stac-extensions.github.io/template/__STAC_VERSION__/schema.json>
Shound'nt be https://linz.github.io/stac/**__STAC_VERSION__/template**/schema.json ?
I mean it does not match with what is in extensions/template/examples/collection.json

2021-09-16 23:47 UTC, paulfouquet commented on extensions/quality/schema.json
> +            "const": "https://linz.github.io/STAC/__STAC_VERSION__/quality/schema.json"
Don't know if it is case sensitive ('STAC')

2021-09-16 23:49 UTC, l0b0 requested changes

2021-09-16 23:49 UTC, l0b0 commented on validate.sh
> +    $@
This line should probably be `${@+"$@"}` to be able to optionally pass arguments with whitespace. Also, there should be a newline at EOF.

2021-09-17 00:11 UTC, l0b0 approved these changes

2021-09-17 00:28 UTC, merged